auth/urls.py
# The views used below are normally mapped in the AdminSite instance.
# This URLs file is used to provide a reliable view deployment for test purposes.
# It is also provided as a convenience to those who want to deploy these URLs
# elsewhere.

from django.contrib.auth import views
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/", views.PasswordChangeView.as_view(), name="password_change"
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

monitoring/urls.py
from django.urls import path,include
from django.conf import settings
from . import views
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import admin
from django.conf.urls.static import static
from .views import download_excel,export_excel,exp_excel,download_report_excel,download_report_pdf,download_masterlist_excel,download_masterlist_pdf,pdf_report_create,pdf_masterlist_create,excel_masterlist_create,logout,PatientListView,pdf_report_create2,pdf_report_create3,pdf_report_create4,pdf_report_create_annual,pdf_cohort_create1,pdf_cohort_create2,pdf_cohort_create3,pdf_cohort_create4,pdf_cohort_create_annual


app_name = 'monitoring'

urlpatterns = [

    #path('locked/', locked_view, name='locked'),
    #path('confirmation/', views.confirm_device, name='confirmation'),
    #path('lock_account/', views.lock_account, name='lock_account'),

    path('patientlistview/',PatientListView.as_view(),name='patientlist'),
    path('',views.index,name='index'),
    path('choropleth_map/',views.choropleth_map,name='choropleth_map'),
    path('admin/', views.admin_redirect, name='admin_redirect'),
    path('admin/logout/', views.logout, name='logout'),
    #path('admin/downloads/', views.table, name='table'),
    path('overview/', views.overview, name='overview'),
    path('overview/choropleth_map/', views.choro, name='choro'),
    path('overview/reports/', views.reports, name='reports'),
    path('overview/tables/', views.tables, name='tables'),
    #path('overview/download/', views.download, name='download'),
    path('overview/download_excel/', download_excel, name='download_excel'),
    path('overview/export_excel/', export_excel, name='export_excel'),
    path('overview/exp_excel/', exp_excel, name='exp_excel'),
    path('download_report_excel/', excel_masterlist_create, name='excel_masterlist_create'),

    #For Report URL
    path('download_report_pdf/', pdf_report_create, name='download_report_pdf'),
    path('download_report_pdf2/', pdf_report_create2, name='download_report_pdf2'),
    path('download_report_pdf3/', pdf_report_create3, name='download_report_pdf3'),
    path('download_report_pdf4/', pdf_report_create4, name='download_report_pdf4'),
    path('download_report_pdf_annual/', pdf_report_create_annual, name='download_report_pdf_annual'),


    #For Cohort URL
    path('download_cohort_pdf1/', pdf_cohort_create1, name='pdf_cohort_create1'),
    path('download_cohort_pdf2/', pdf_cohort_create2, name='pdf_cohort_create2'),
    path('download_cohort_pdf3/', pdf_cohort_create3, name='pdf_cohort_create3'),
    path('download_cohort_pdf4/', pdf_cohort_create4, name='pdf_cohort_create4'),
    path('download_cohort_pdf_annual/', pdf_cohort_create_annual, name='pdf_cohort_create_annual'),



    path('download_masterlist_excel/', download_masterlist_excel, name='download_masterlist_excel'),
    path('download_masterlist_pdf/', pdf_masterlist_create, name='download_masterlist_pdf'),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from monitoring.views import overview,choro,reports,tables,download,logout,cohort,download_report_pdf,pdf_report_create
#from monitoring.admin import custom_admin_site

urlpatterns = [
    path('admin/overview/', overview, name='overview'),
    path('admin/overview/choropleth_map/', choro, name='choro'),
    path('admin/overview/reports/', reports, name='reports'),
    #path('admin/overview/download_report_pdf/', pdf_report_create, name='download_report_pdf'),
    path('admin/overview/tables/', tables, name='tables'),
    path('admin/overview/masterlist/', download, name='download'),
    path('admin/overview/cohort/', cohort, name='cohort'),
    path('admin/logout/',logout,name="logout"),
    path('admin/', admin.site.urls),

    path('',include('monitoring.urls')),
    #path('admin/downloads/', custom_admin_site.admin_view(views.table), name='admin_downloads'),  # Custom admin downloads view
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/_indexnav.html
{% load static %}

<link rel="stylesheet" href="{% static 'assets/css/navlink.css' %}">

<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-lg fixed-top" id="fixed-navbar">
    <div class="container-fluid">
        <!-- Logo and Title -->
        <a class="navbar-brand d-flex align-items-center" href="#">
            <img src="{% static 'assets/images/3.jpeg' %}" alt="Logo" class="rounded-circle navbar-brand-logo ms-2" style="width: 50px; height: 50px;">
            <span class="text-primary font-weight-bold ms-2" style="font-size: 24px; margin-left: 10px;">Animal Bite and Rabies Monitoring System-GEO Mapping</span>
        </a>

        <!-- Toggler button for mobile view -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar links and items -->
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                    <a class="nav-link links {% if request.path == '/' %}active{% endif %}" href="/">Overview</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link links {% if request.path == '/choropleth_map/' %}active{% endif %}" href="/choropleth_map">Choropleth Map</a>
                </li>
            </ul>

            <!-- Admin dropdown on the right -->
            <ul class="navbar-nav ms-auto">
                <div class="topbar-divider d-none d-sm-block"></div>
                <li class="nav-item no-arrow">
                    <a class="nav-link m-3" href="{% url 'monitoring:admin_redirect' %}" id="home-admin">
                        <span class="mr-2 text-gray-600">Login</span>
                        <i class="fas fa-user" id="home-icon-admin"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/partials/_navlink.html
{% load static %}

<!-- Navbar HTML -->
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-lg fixed-top" id="fixed-navbar">
    <div class="container-fluid">
        <!-- Logo and Title -->
        <a class="navbar-brand d-flex align-items-center" href="#">
            <img src="{% static 'assets/images/3.jpeg' %}" alt="Logo" class="rounded-circle" style="width: 40px; height: 40px;">
            <span class="text-primary ms-2" style="font-size: 24px;"><i>ABRMS-GEO Mapping</i></span>
        </a>

        <!-- Toggler button for mobile view -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar links and items -->
        <div class="collapse navbar-collapse" id="navbarNav">
            <!-- Centered Navbar Links (for larger screens) -->
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link text-primary custom-hover {% if request.path == '/admin/overview/' %}active{% endif %}" href="{% url 'overview' %}">Overview</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-primary custom-hover {% if request.path == '/admin/overview/choropleth_map/' %}active{% endif %}" href="{% url 'choro' %}">Choropleth Map</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-primary custom-hover {% if request.path == '/admin/overview/tables/' %}active{% endif %}" href="{% url 'tables' %}">Table</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-primary custom-hover {% if request.path == '/admin/overview/reports/' %}active{% endif %}" href="{% url 'reports' %}">Report</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-primary custom-hover {% if request.path == '/admin/overview/cohort/' %}active{% endif %}" href="{% url 'cohort' %}">Cohort</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-primary custom-hover {% if request.resolver_match.url_name == 'download' %}active{% endif %}" href="{% url 'download' %}">Master List</a>
                </li>
            </ul>

            <!-- User Profile and Dropdown (Aligned Right) -->
            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link d-flex align-items-center" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <span class="d-none d-lg-inline me-2" style="font-size: 16px; color: rgb(38, 38, 72);">
                            {% if request.user.is_superuser %}
                                admin
                            {% else %}
                                {{ request.user.username }}
                            {% endif %}
                        </span>
                        <i class="fas fa-user"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                        <li><a class="dropdown-item" href="/admin/"><i class="fas fa-arrow-left fa-sm fa-fw text-gray-400"></i> Back</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'monitoring:logout' %}"><i class="fas fa-door-open fa-sm fa-fw text-gray-400"></i> Logout</a></li>
                    </ul>
                </li>                
            </ul>
        </div>
    </div>
</nav>


<!-- Custom CSS -->
<style>
    @media (max-width: 991px) {
        .navbar-nav {
            text-align: right; /* Align navbar items to the right */
        }
        .fa-user {
            text-align: right; /* Align navbar items to the right */
        }
        .navbar-toggler-icon {
            background-color: white; /* Make the toggle icon visible against the red background */
        }
        .dropdown-menu {
            background-color: white !important; /* Set red background for mobile view */
            text-align: right; /* Align navbar items to the right */
        }

    }
    /* Initial color is black */
    .nav-link.custom-hover {
        color: black !important;
        text-decoration: none;
    }


    .nav-link.custom-hover:hover {
        text-decoration: underline;
    }

    /* Active link: blue color */
    .nav-link.active {
        color: #007bff !important; /* Blue color when active */
        text-decoration: underline;
    }

</style>

templates/partials/p.html
{% load static %}


<nav class="navbar navbar-expand navbar-light bg-white mb-4 topbar fixed-top " id="fixed-navbar"><!-- fixed-top static-top -->
    <img src="{% static 'assets/images/3.jpeg' %}" alt="Logo" class="rounded-circle mr-4" id="responsive-image" style="width: 55px; height: 55px;">
    <span class="text-primary font-weight-bold d-inline-block d-md-inline col-sm-8 col-lg-9 col-md-8" id="responsive-text">Animal Bite and Rabies Monitoring System with GEO Mapping</span>
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <div class="topbar-divider d-none d-sm-block"></div>
        <li class="nav-item no-arrow">
            <a class="nav-link m-3" href="{% url 'monitoring:admin_redirect' %}" id="home-admin">
                <span class="mr-2   text-gray-600">Login</span>
                <i class="fas fa-user " id="home-icon-admin"></i>
            </a>
        </li>
    </ul>
</nav>
<style>
    #fixed-navbar {
    padding: 10px 20px; /* Adds some padding inside the navbar */
    margin-bottom:  1000px; /* Adds margin on the left and right to prevent the navbar from sticking to the edges */
    z-index: 1030; /* Ensure the navbar stays above other elements */
}
</style>

{% load static %}

    <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-lg pb-2 fixed-top " id="fixed-navbar">
        <!-- ABRMS-GEO Mapping on the left -->
        <div class="d-flex align-items-center">
            <img src="{% static 'assets/images/3.jpeg' %}" alt="Logo" class="rounded-circle navbar-brand-logo ms-2" style="width: 50px; height: 50px;">
            <span class="text-primary font-weight-bold ms-2" style="font-size: 30px;">ABRMS-GEO Mapping</span>
        </div>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar content: centered links and admin on the right -->
        <div class="collapse navbar-collapse" id="navbarNav">
            <!-- Centered Navigation Links -->
            <div class="mx-auto">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link links {% if request.path == '/overview/' %}active{% endif %}" href="/overview/">Overview</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link links {% if request.path == '/overview/choropleth_map/' %}active{% endif %}" href="/overview/choropleth_map">Choropleth Map</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link links {% if request.path == '/overview/reports/' %}active{% endif %}" href="/overview/reports/">Reports</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link links {% if request.path == '/overview/tables/' %}active{% endif %}" href="/overview/tables/">Tables</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link links {% if request.path == '/overview/download/' %}active{% endif %}" href="/overview/download/">Download</a>
                    </li>
                </ul>
            </div>

            <!-- Admin dropdown on the right -->
            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <span class="mr-2 d-none d-lg-inline admin" id="download-admin" >
                            {% if request.user.is_superuser %}
                                admin
                            {% else %}
                            <span style="font-size: 16px; color: rgb(38, 38, 72);" >{{ request.user.username }}</span> 
                            {% endif %}
                        </span>
                        <i class="fas fa-user" id="download-icon-admin"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                        <li><a class="dropdown-item" href="/admin/"><i class="fas fa-arrow-left fa-sm fa-fw mr-2 text-gray-400"></i> Back</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'monitoring:logout' %}"><i class="fas fa-door-open fa-sm fa-fw mr-2 text-gray-400"></i> Logout</a></li>
                    </ul>
                </li>                
            </ul>

        </div>
    </nav>
<style>
    .links {
        font-weight: 500 !important;
        color: rgb(56, 56, 56) !important;
        font-size: 15px !important;
        margin-right: 2px !important;
    }

    .links:hover {
        color: #007bff !important; /* Blue color for hover */
        font-weight: bold;
        border-bottom: 2px solid #007bff; /* Underline effect */
    }

    /* Active state */
    .links.active {
        color: #007bff !important; /* Blue color for active link */
        font-weight: bold;
        border-bottom: 2px solid #007bff; /* Underline effect for active link */
    }

    .admin {
        font-size: 18px !important;
        color: black !important;
    }

    .dropdown-menu {
        z-index: 1050; /* Ensure the dropdown is above other elements */
    }

    /* Example CSS for Navbar */
    
    
    #fixed-navbar {
        padding: 10px 20px; /* Adds some padding inside the navbar */
        margin-bottom:  1000px; /* Adds margin on the left and right to prevent the navbar from sticking to the edges */
        z-index: 1030; /* Ensure the navbar stays above other elements */
    }

    /* Add some top margin to the content below the navbar */
    body {
        padding-top: 80px; /* Adjust this value to the height of your navbar */
    }
</style>