auth/urls.py
# The views used below are normally mapped in the AdminSite instance.
# This URLs file is used to provide a reliable view deployment for test purposes.
# It is also provided as a convenience to those who want to deploy these URLs
# elsewhere.

from django.contrib.auth import views
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/", views.PasswordChangeView.as_view(), name="password_change"
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

monitoring/urls.py
from django.urls import path,include
from django.conf import settings
from . import views
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import admin
from django.conf.urls.static import static
from .views import download_excel,export_excel,exp_excel,download_report_excel,download_report_pdf,download_masterlist_excel,download_masterlist_pdf,pdf_report_create,pdf_masterlist_create,excel_masterlist_create,logout,PatientListView,pdf_report_create2,pdf_report_create3,pdf_report_create4,pdf_report_create_annual,pdf_cohort_create1,pdf_cohort_create2,pdf_cohort_create3,pdf_cohort_create4,pdf_cohort_create_annual


app_name = 'monitoring'

urlpatterns = [

    #path('locked/', locked_view, name='locked'),
    #path('confirmation/', views.confirm_device, name='confirmation'),
    #path('lock_account/', views.lock_account, name='lock_account'),

    path('patientlistview/',PatientListView.as_view(),name='patientlist'),
    path('',views.index,name='index'),
    path('choropleth_map/',views.choropleth_map,name='choropleth_map'),
    path('admin/', views.admin_redirect, name='admin_redirect'),
    path('admin/logout/', views.logout, name='logout'),
    #path('admin/downloads/', views.table, name='table'),
    path('overview/', views.overview, name='overview'),
    path('overview/choropleth_map/', views.choro, name='choro'),
    path('overview/reports/', views.reports, name='reports'),
    path('overview/tables/', views.tables, name='tables'),
    #path('overview/download/', views.download, name='download'),
    path('overview/download_excel/', download_excel, name='download_excel'),
    path('overview/export_excel/', export_excel, name='export_excel'),
    path('overview/exp_excel/', exp_excel, name='exp_excel'),
    path('download_report_excel/', excel_masterlist_create, name='excel_masterlist_create'),

    #For Report URL
    path('download_report_pdf/', pdf_report_create, name='download_report_pdf'),
    path('download_report_pdf2/', pdf_report_create2, name='download_report_pdf2'),
    path('download_report_pdf3/', pdf_report_create3, name='download_report_pdf3'),
    path('download_report_pdf4/', pdf_report_create4, name='download_report_pdf4'),
    path('download_report_pdf_annual/', pdf_report_create_annual, name='download_report_pdf_annual'),


    #For Cohort URL
    path('download_cohort_pdf1/', pdf_cohort_create1, name='pdf_cohort_create1'),
    path('download_cohort_pdf2/', pdf_cohort_create2, name='pdf_cohort_create2'),
    path('download_cohort_pdf3/', pdf_cohort_create3, name='pdf_cohort_create3'),
    path('download_cohort_pdf4/', pdf_cohort_create4, name='pdf_cohort_create4'),
    path('download_cohort_pdf_annual/', pdf_cohort_create_annual, name='pdf_cohort_create_annual'),



    path('download_masterlist_excel/', download_masterlist_excel, name='download_masterlist_excel'),
    path('download_masterlist_pdf/', pdf_masterlist_create, name='download_masterlist_pdf'),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from monitoring.views import overview,choro,reports,tables,download,logout,cohort,download_report_pdf,pdf_report_create
#from monitoring.admin import custom_admin_site

urlpatterns = [
    path('admin/overview/', overview, name='overview'),
    path('admin/overview/choropleth_map/', choro, name='choro'),
    path('admin/overview/reports/', reports, name='reports'),
    #path('admin/overview/download_report_pdf/', pdf_report_create, name='download_report_pdf'),
    path('admin/overview/tables/', tables, name='tables'),
    path('admin/overview/masterlist/', download, name='download'),
    path('admin/overview/cohort/', cohort, name='cohort'),
    path('admin/logout/',logout,name="logout"),
    path('admin/', admin.site.urls),

    path('',include('monitoring.urls')),
    #path('admin/downloads/', custom_admin_site.admin_view(views.table), name='admin_downloads'),  # Custom admin downloads view
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

monitoring/views.py
import io
from io import BytesIO  
import os  
import pdfkit
import json

from urllib.parse import urlencode
from datetime import datetime, timedelta, date
from dateutil.relativedelta import relativedelta 
from calendar import month_name

# Django imports
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.db.models import Count, F, Sum, Q
from django.db.models.functions import ExtractWeek, ExtractYear, ExtractDay, ExtractMonth, TruncDay, TruncDate, TruncMonth, TruncQuarter, TruncYear
from django.utils import timezone
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import get_user_model, logout as auth_logout
from django.contrib import messages
from django.contrib.admin.models import LogEntry
from django.contrib.auth.models import Group, User as AuthUser
from django.template.loader import get_template, render_to_string
from django.core.serializers import serialize
from django.db import models
from django.contrib.gis.geos import GEOSGeometry
from django.template import loader

# Third-party libraries
import pandas as pd
import openpyxl  # Import the openpyxl library
from openpyxl import Workbook
from openpyxl.drawing.image import Image as OpenpyxlImage
from openpyxl.styles import Font, Alignment
from openpyxl.utils import get_column_letter
import PyPDF2
from fpdf import FPDF
import xhtml2pdf.pisa as pisa
#from weasyprint import HTML

# Local imports
from .models import Patient, History, Treatment, Barangay, Municipality, User,Doctor
from .forms import FormatForm
from .admin import PatientResource

# Python collections
from collections import Counter

# Django views
from django.views.generic import ListView, FormView

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WKHTMLTOPDF_PATH = os.path.join(BASE_DIR, 'bin', 'wkhtmltopdf.exe')


class PatientListView(ListView, FormView):
    model = Patient
    template_name = 'monitoring/listview.html'
    form_class = FormatForm

    def post(self, request, *args, **kwargs):
        qs = self.get_queryset()
        dataset = PatientResource().export(qs)

        # Retrieve the selected format
        format = request.POST.get('format')
        
        # Select the format for the dataset export
        if format == 'xls':
            ds = dataset.export('xlsx')  # Export to xlsx (for Excel)
            content_type = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
            file_extension = 'xlsx'
        elif format == 'csv':
            ds = dataset.export('csv')  # Export to CSV
            content_type = 'text/csv'
            file_extension = 'csv'
        else:
            ds = dataset.export('json')  # Export to JSON
            content_type = 'application/json'
            file_extension = 'json'

        # Set the content type and download file name
        response = HttpResponse(ds, content_type=content_type)
        response['Content-Disposition'] = f'attachment; filename="patients.{file_extension}"'
        return response

def paginate_histories(histories):
    pages = []
    current_page = []
    max_rows_13 = 10  # Maximum rows for pages meant to hold smaller groups
    max_rows_15 = 15  # Maximum rows for other pages
    current_row_count = 0  # Counter to keep track of rows in the current page

    for history in histories:
        if current_row_count < max_rows_13:
            max_rows = max_rows_13
        else:
            max_rows = max_rows_15

        current_page.append(history)
        current_row_count += 1

        if len(current_page) >= max_rows:
            pages.append(current_page)
            current_page = []
            current_row_count = 0  # Reset row counter for the new page

    if current_page:  # Add remaining rows to the last page
        pages.append(current_page)

    return pages


def excel_masterlist_create(request):
    # Get the current user
    user = request.user

    # Get selected filters from request
    selected_municipality = request.GET.get('municipality')
    selected_barangay = request.GET.get('barangay')
    selected_user = request.GET.get('searchUsername') 
    start_month = request.GET.get('startMonth')
    end_month = request.GET.get('endMonth')
    search_name = request.GET.get('searchName')
    
    # Fetch the histories with related patient, municipality, and barangay data
    histories = History.objects.select_related('patient_id', 'muni_id', 'brgy_id').order_by('-registration_no')

    if not user.is_superuser:
        # Filter histories for the current user if not a superuser
        histories = histories.filter(patient_id__user=user)
    
    # Apply filters based on selected municipality and barangay
    if selected_municipality:
        histories = histories.filter(muni_id=selected_municipality)
    if selected_barangay:
        histories = histories.filter(brgy_id=selected_barangay)

    # Apply filter based on username search only if user is a superuser
    if user.is_superuser and selected_user:
        histories = histories.filter(patient_id__user__username=selected_user)
    
    # Apply filter based on selected start and end months
    if start_month and end_month:
        try:
            current_year = timezone.now().year
            start_date = datetime.strptime(f"{start_month} {current_year}", "%B %Y").replace(day=1)
            end_date = datetime.strptime(f"{end_month} {current_year}", "%B %Y").replace(day=1) + relativedelta(months=1) - relativedelta(days=1)
            histories = histories.filter(date_registered__gte=start_date, date_registered__lte=end_date)
        except Exception as e:
            print(f"Error parsing date: {e}")

    # Apply filter based on name search
    if search_name:
        histories = histories.filter(Q(patient_id__first_name__icontains=search_name) | Q(patient_id__last_name__icontains=search_name))

    # Prepare data for Excel
    data = []
    for history in histories:
        age = calculate_age(history.patient_id.birthday)
        treatment = Treatment.objects.filter(patient_id=history.patient_id).first()
        data.append({
            'Registration No': history.registration_no,
            'Patient Name': f"{history.patient_id.first_name} {history.patient_id.last_name}",
            'Municipality': history.muni_id.muni_name,
            'Barangay': history.brgy_id.brgy_name,
            'Date Registered': history.date_registered,
            'Age': age,
            'Treatment': treatment.vaccine_generic_name if treatment else '',
            'Sex': history.patient_id.sex,
            'Source of Exposure': history.source_of_exposure
        })

    # Create a DataFrame from the data
    df = pd.DataFrame(data)

    # Create an Excel response
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = ' filename="masterlist.xlsx"'#attachment;

    # Write the DataFrame to the Excel response
    with pd.ExcelWriter(response, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Masterlist')

    return response

# Function to read data from Excel
def read_excel(file_path):
    df = pd.read_excel(file_path)
    return df

# Function to read data from PDF
def read_pdf(file_path):
    pdf_reader = PyPDF2.PdfFileReader(file_path)
    text = ""
    for page_num in range(pdf_reader.numPages):
        page = pdf_reader.getPage(page_num)
        text += page.extract_text()
    return text

# Function to generate PDF report
def generate_pdf_report(excel_data, pdf_data, output_path):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # Add Excel data to PDF
    pdf.cell(200, 10, txt="Excel Data", ln=True, align='C')
    for i in range(len(excel_data)):
        pdf.cell(200, 10, txt=str(excel_data.iloc[i].to_dict()), ln=True)

    # Add PDF data to PDF
    pdf.add_page()
    pdf.cell(200, 10, txt="PDF Data", ln=True, align='C')
    pdf.multi_cell(0, 10, pdf_data)

    pdf.output(output_path)

def index(request):
    # Retrieve all totals
    total_patients = Patient.objects.count()
    total_history = History.objects.count()
    total_treatments = Treatment.objects.count()

    # Count male and female patients
    male_patients = Patient.objects.filter(sex='male').count()
    female_patients = Patient.objects.filter(sex='female').count()

    # Calculate counts for different animal bites
    dog_bites = History.objects.filter(source_of_exposure='Dog').count()
    cat_bites = History.objects.filter(source_of_exposure='Cat').count()
    
    # Perform a query to count the occurrences of each municipality of exposure
    municipality_exposures = History.objects.values('muni_id__muni_name').annotate(count=Count('muni_id')).order_by('-count').first()

    # Determine which animal has the highest count
    animal_counts = History.objects.values('source_of_exposure').annotate(count=Count('source_of_exposure')).order_by('-count').first()
    most_cases_animal = animal_counts

    gender_counts = Patient.objects.values('sex').annotate(count=Count('sex')).order_by('-count').first()

    histories = History.objects.all()  # Retrieve all Histories from the database

    # Count the number of male and female patients
    gender = Patient.objects.values('sex').annotate(count=Count('sex')).order_by('sex')
    
    gen = [data['sex'].capitalize() for data in gender]
    dataGender = [data['count'] for data in gender]

    # Count the number animal source of exposure
    source_exposure = History.objects.values('source_of_exposure').annotate(count=Count('source_of_exposure')).order_by('source_of_exposure')
    
    animal = [data['source_of_exposure'].capitalize() for data in source_exposure]

templates/monitoring/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ABRMS-GEO Mapping | {% block title %} {% endblock %}</title>
    
    <link href="{% static 'assets/images/seal.png' %}" rel="icon" type="image/png">
    <link href="{% static 'strap/css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">  


    <!-- JavaScript-->
    <script src="{% static 'strap/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'strap/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />

    <link href="{% static 'assets/images/seal.png' %}" rel="icon" type="image/png">

    <!-- Custom fonts for this template-->
    <link href="{% static 'strap/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    
    <!-- Font Awesome Icons -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    
    
    <link rel="stylesheet" href="{% static 'assets/css/_navlink.css' %}">

    <!-- Include Bootstrap CSS -->
    <!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet"> -->


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    

    {% block style %}{% endblock %}


    
</head>
<body>
    <div class="container-fluid mt-2">
        <div class="row">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    
        {% block chart %}
        {% endblock %}
        
{% block script %}
{% endblock %}


<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>

</body>
</html>

templates/monitoring/cohort.html
{% extends "monitoring/base.html" %}

{% load static%}
{% block title %}
Cohort
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'assets/css/cohort.css' %}">
{% endblock %}

{% block content %}
{% include "partials/_navlink.html" %}
<div class="text-end mb-4 me-5">
    {% if selected_quarter == '1' %}
        <a href="{% url 'monitoring:pdf_cohort_create1' %}" target="_blank" class="btn btn-success me-2" style="width: 100px;">
            <i class="fas fa-download me-2"></i> PDF
        </a>
    {% elif selected_quarter == '2' %}
        <a href="{% url 'monitoring:pdf_cohort_create2' %}" target="_blank" class="btn btn-success me-2" style="width: 100px;">
            <i class="fas fa-download me-2"></i> PDF
        </a>
    {% elif selected_quarter == '3' %}
        <a href="{% url 'monitoring:pdf_cohort_create3' %}" target="_blank" class="btn btn-success me-2" style="width: 100px;">
            <i class="fas fa-download me-2"></i> PDF
        </a>
    {% elif selected_quarter == '4' %}
        <a href="{% url 'monitoring:pdf_cohort_create4' %}" target="_blank" class="btn btn-success me-2" style="width: 100px;">
            <i class="fas fa-download me-2"></i> PDF
        </a>
    {% elif selected_quarter == 'annual' %}
        <a href="{% url 'monitoring:pdf_cohort_create_annual' %}" target="_blank" class="btn btn-success me-2" style="width: 100px;">
            <i class="fas fa-download me-2"></i> PDF
        </a>
    {% endif %}
</div>

<form method="get" class="form-group mb-4 ms-5">
        <div class="mb-3 text-center">
            <!-- <label for="quarter" class="form-label">Select Quarter:</label> -->
            <div class="input-group justify-content-center select-width">
                <select name="quarter" id="quarter" class="form-select"   onchange="this.form.submit()">
                    <option value="1" {% if selected_quarter == '1' %}selected{% endif %}>1st Quarter</option>
                    <option value="2" {% if selected_quarter == '2' %}selected{% endif %}>2nd Quarter</option>
                    <option value="3" {% if selected_quarter == '3' %}selected{% endif %}>3rd Quarter</option>
                    <option value="4" {% if selected_quarter == '4' %}selected{% endif %}>4th Quarter</option>
                    <option value="annual" {% if selected_quarter == 'annual' %}selected{% endif %}>Annual</option>
                </select>
                <span class="input-group-text"><i class="bi bi-calendar2-check"></i></span>
            </div>
        </div>
    </form>
<div class="p-2">
    <div class="d-flex justify-content-start align-items-start mb-4"> <!-- Logo on the left, text centered -->
        <div class="d-flex align-items-center">
            <div class="d-flex align-items-center">
                {% if logo_url  %}
                    <img src="{{ logo_url }}" alt="Logo" style="height: 120px; margin-right: 20px; margin-left: 20px;">
                {% else %}
                    <p>No logo available</p>
                {% endif %}
            </div>
        </div>
        <!-- Adjusted the text container to be centered -->
        <div class="text-center quarter mx-auto" style="flex-grow: 1;"> 
            <h1 class="h3">POST-EXPOSURE PROPHYLAXIS COHORT REPORT FORM</h1>
            {% if user.is_superuser %}
                <h2 class="h4" style="margin: 0;">Province of Biliran</h2>
            {% else %}
                <h2 class="h4" style="margin: 0;">Municipality of {{ municipality_name }}</h2>
            {% endif %}
            <h3 class="h5" style="margin: 0;">
                <u>
                    {{ report_title }}
                </u>
            </h3>
        </div>
    </div>
    <table class="table table-bordered table-striped">
        <thead style=text-align:center;>
            <tr>
                <th rowspan="2">Category of Exposure</th>
                <th rowspan="2">No. of Registered Exposure</th>
                <th rowspan="2">Number of Patients who received RIG</th>
                <th colspan="4">Outcome of Post-Exposure Prophylaxis</th>
            </tr>
            <tr>
                <th>Complete</th>
                <th>Incomplete</th>
                <th>None</th>
                <th>Died</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Category II</td>
                <td>{{ category_ii_count }}</td>
                <td>{{ category_ii_with_rig }}</td>
                <td>{{ category_ii_complete }}</td>
                <td>{{ category_ii_incomplete }}</td>
                <td>{{ category_ii_none }}</td>
                <td>{{ category_ii_died }}</td>
            </tr>
            <tr>
                <td>Category III</td>
                <td>{{ category_iii_count }}</td>
                <td>{{ category_iii_with_rig }}</td>
                <td>{{ category_iii_complete }}</td>
                <td>{{ category_iii_incomplete }}</td>
                <td>{{ category_iii_none }}</td>
                <td>{{ category_iii_died }}</td>
            </tr>
            <tr>
                <td>Total</td>
                <td>{{ total_count }}</td>
                <td>{{ total_count_rig }}</td>
                <td>{{ total_complete }}</td>
                <td>{{ total_incomplete }}</td>
                <td>{{ total_none }}</td>
                <td>{{ total_died }}</td>
            </tr>
        </tbody>
    </table>
    <div class="signature-section mt-5">
        <div class="signatures">
            <div class="prepared">
                <p class="label">Prepared By:</p>
                <div class="signature-line">
                    <span class="signature-name">{{ signature_name }}</span>
                    <div class="line"></div>
                </div>
                <p class="signature-title">{{ coordinator }}</p>
            </div>
            <div class="noted">
                <p class="label">Noted By:</p>
                <div class="signature-line">
                    <span class="signature-name">{{ doctor }}</span>
                    <div class="line"></div>
                </div>
                <p class="signature-title">{{ pho }}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{% endblock %}

templates/monitoring/confirmation_email.html
_<!DOCTYPE html>
<html>
<head>
    <title>Is this your device?</title>
</head>
<body>
    <h3>Is this your device?</h3>
    <p>Hello {{ user.username }},</p>
    <p>We noticed a failed login attempt. If this was you, please ignore this email. If not, please click "No" below to lock your account.</p>

    <p>
        <a href="{% url 'monitoring:lock_account' %}?confirmation=yes">Yes</a>
        <a href="{% url 'monitoring:lock_account' %}?confirmation=no">No</a>
    </p>
</body>
</html>

templates/monitoring/listview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container mt-5">
    <h2 class="mb-4">Patient List</h2>
    
    <!-- Table -->
    {% if object_list %}
    <table class="table table-bordered table-striped">
        <thead class="table-dark">
            <tr>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Last Name</th>
                <th>Municipality</th>
                <th>Barangay</th>
                <th>Doctor</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object_list %}
                <tr>
                    <td>{{ obj.first_name }}</td>
                    <td>{{ obj.middle_name }}</td>
                    <td>{{ obj.last_name }}</td>
                    <td>{{ obj.muni_id }}</td>
                    <td>{{ obj.brgy_id }}</td>
                    <td>{{ obj.doctor }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>No patients available</p>
    {% endif %}

    <!-- Trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#download-modal">
        Download
    </button>

    <!-- Modal -->
    <div class="modal fade" id="download-modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Download Patient List</h5>
                    <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Download</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>